# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Avalon Now
tagline:          'Volunteers for a Better Community'
description:      'Avalon Now is a group that aims to bring together the talents, resources, and skills of people in the community in order to increase their collective power and work for positive change.'
url:              https://pagewaiter.github.io/avalonnow
baseurl:          https://pagewaiter.github.io/avalonnow/

author:
  name:           'Jason Mosley'
  url:            https://www.pagewaiter.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Pagewaiter/avalonnow
